### PR TITLE
use pyscrypt instead of scrypt

### PR DESCRIPTION
**Pull request by x-falcon**
add log stand out print

### CODE REVIEW

**Comment by mccwdev** [comment]
What is your reason to prefer pyscrypt over scrypt? In my configuration it takes several minutes to decrypt a key and the unittests take up to 40 minutes instead of 5-6 minutes https://travis-ci.org/1200wd/bitcoinlib/builds/469411402. Maybe there is a way around this?

**Comment by x-falcon** [comment]
because many user failed to install scrypt , the  pyscrypt  use pure-python implementation,easy install.
but i don't know why it's so slow.

**Comment by mccwdev** [comment]
We could allow the use of both libraries? See which one is installed when running bitcoinlib, try scrypt first and then pyscript. Scrypt is only used for BIP38 encrypted keys and not everyone needs these as well.

**Comment by x-falcon** [comment]
good idea

**Pull request closed without merging**
