### PR TITLE
Defer the creation of the config directory until requested

### PR DESCRIPTION
**Pull request by HoverHell**

### CODE REVIEW

**Comment by mccwdev** [comment]
Tried to merge this to test, but couldn't get it to work.
Database is set to None / test/None when unittesting, and logs are send to stdout.
Also logs username / password when used in database uri

**Comment by HoverHell** [comment]
I've rebased these changes onto the current `master`. Tests seem to mostly work.

> None / test/None when unittesting

Which tests cause that?

**Comment by mccwdev** [comment]
> Which tests cause that?

Some local test with python -m unittest. Could also be a local problem, I test it again with the fixed PR.

**Comment by mccwdev** [comment]
Sorry, I've reverted the PR, was not able to get it working.

Not all global variables where available everywhere resulting in creating of database 'None' and not being able to find local files, as you can see for instance in https://github.com/1200wd/bitcoinlib/actions/runs/9366996897

**Pull request merged**
